#!/bin/bash

# ═════════════════════════════════════════════════════════════════════════════
#    SCRIPT DE AYUDA - PUBLICAR DASHBOARD EN STREAMLIT CLOUD
# ═════════════════════════════════════════════════════════════════════════════
#
# Este script te ayuda a publicar tu dashboard en Streamlit Community Cloud
# gratis y con una URL pública.
#
# ⏱️  Tiempo total: 5-10 minutos
# 💰 Costo: Completamente GRATIS
# 🎯 Resultado: Dashboard en vivo con URL pública
#
# ═════════════════════════════════════════════════════════════════════════════

echo ""
echo "╔════════════════════════════════════════════════════════════════════════╗"
echo "║                                                                        ║"
echo "║      🚀 GUÍA DE PUBLICACIÓN - STREAMLIT COMMUNITY CLOUD 🚀            ║"
echo "║                                                                        ║"
echo "║         Dashboard E-Commerce de Ventas - Producción Ready             ║"
echo "║                                                                        ║"
echo "╚════════════════════════════════════════════════════════════════════════╝"
echo ""

echo "PASO 1️⃣ : CREAR REPOSITORIO EN GITHUB"
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "1. Abre: https://github.com/new"
echo "2. Rellena estos datos:"
echo "   • Repository name: E-Commerce-Dashboard"
echo "   • Description: Dashboard interactivo de ventas E-Commerce con Streamlit"
echo "   • Public: ✓ (debe ser público para Streamlit Cloud)"
echo "   • Add .gitignore: Selecciona 'Python'"
echo ""
echo "3. Click en 'Create repository'"
echo ""
echo "⏸️  PAUSA: Vuelve aquí cuando tengas creado el repositorio"
read -p "Presiona ENTER para continuar..."
echo ""

echo "PASO 2️⃣ : CONFIGURAR GIT LOCALMENTE"
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "Ejecuta estos comandos en tu terminal:"
echo ""

echo "# Navega a la carpeta del proyecto"
echo "cd \"/home/fabian/data science/project3\""
echo ""

echo "# Inicializa git (si no está ya inicializado)"
echo "git init"
echo ""

echo "# Añade todos los archivos"
echo "git add ."
echo ""

echo "# Haz el primer commit"
echo 'git commit -m "Initial commit: Dashboard E-Commerce profesional"'
echo ""

echo "# Cambia a rama 'main' (si es necesario)"
echo "git branch -M main"
echo ""

echo "# Conecta con tu repositorio de GitHub (reemplaza valores)"
echo "# Copia esto y REEMPLAZA <USERNAME> y deja 'E-Commerce-Dashboard'"
echo "git remote add origin https://github.com/<TU_USERNAME>/E-Commerce-Dashboard.git"
echo ""

echo "# Sube los cambios a GitHub"
echo "git push -u origin main"
echo ""

echo "⏸️  PAUSA: Ejecuta los comandos de arriba antes de continuar"
read -p "Presiona ENTER cuando hayas subido a GitHub..."
echo ""

echo "PASO 3️⃣ : VERIFICAR EN GITHUB"
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "1. Abre: https://github.com/<TU_USERNAME>/E-Commerce-Dashboard"
echo "2. Verifica que ves:"
echo "   ✓ dashboard.py"
echo "   ✓ data.csv"
echo "   ✓ requirements.txt"
echo "   ✓ README.md"
echo "   ✓ .gitignore"
echo ""
echo "Si ves todos los archivos ✓, continúa al PASO 4"
echo ""
echo "⏸️  PAUSA: Verifica que GitHub tiene todos los archivos"
read -p "Presiona ENTER cuando hayas verificado..."
echo ""

echo "PASO 4️⃣ : CREAR CUENTA EN STREAMLIT CLOUD"
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "1. Abre: https://share.streamlit.io"
echo "2. Click en 'Sign Up' (o 'Log In' si ya tienes cuenta)"
echo "3. Usa tu cuenta de GitHub para loguarte (más fácil)"
echo ""
echo "⏸️  PAUSA: Crea tu cuenta en Streamlit Cloud"
read -p "Presiona ENTER cuando tengas cuenta..."
echo ""

echo "PASO 5️⃣ : DESPLEGAR EN STREAMLIT CLOUD"
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "1. En Streamlit Cloud, haz click en 'New app'"
echo "2. Conecta tu GitHub (autoriza la aplicación)"
echo "3. Selecciona:"
echo "   • Repository: <TU_USERNAME>/E-Commerce-Dashboard"
echo "   • Branch: main"
echo "   • Main file path: dashboard.py"
echo ""
echo "4. Click en 'Deploy'"
echo ""
echo "✏️  NOTA: Streamlit empezará a descargar y ejecutar tu app"
echo "        Esto tarda 2-5 minutos la primera vez"
echo ""

echo "PASO 6️⃣ : ¡LISTO! TU DASHBOARD ESTÁ EN VIVO"
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "Una vez desplegado, podrás acceder desde:"
echo ""
echo "🌐 https://<TU_USERNAME>-e-commerce-dashboard.streamlit.app/"
echo ""
echo "(Streamlit generará la URL exacta - la verás en el dashboard)"
echo ""

echo "CARACTERÍSTICAS DE TU DASHBOARD:"
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "✓ URL pública y compartible"
echo "✓ Acceso gratuito desde cualquier navegador"
echo "✓ Filtros dinámicos (País, Fechas, Cantidad)"
echo "✓ 5 gráficos profesionales interactivos"
echo "✓ KPIs en tiempo real"
echo "✓ Descarga de datos (CSV y Excel)"
echo "✓ Auto-deploy: cambios en GitHub → auto-update en Cloud"
echo ""

echo "PRÓXIMOS PASOS:"
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "1. 🔗 Comparte tu URL en LinkedIn"
echo "   Ejemplo: 'Hice un dashboard de análisis de ventas con Streamlit'"
echo ""
echo "2. 🎨 Personaliza colores (edita dashboard.py y haz git push)"
echo ""
echo "3. 📊 Agrega más gráficos (edita dashboard.py)"
echo ""
echo "4. 🗄️  Conecta a base de datos SQL (en lugar de CSV)"
echo ""

echo "SOLUCIÓN DE PROBLEMAS:"
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "❌ ERROR: 'data.csv not found'"
echo "   ✓ Verifica que data.csv está en el repo de GitHub"
echo ""
echo "❌ ERROR: 'Module not found'"
echo "   ✓ Actualiza requirements.txt con todas las dependencias"
echo ""
echo "❌ Dashboard es MUY LENTO"
echo "   ✓ Streamlit Cloud tiene límites de recursos"
echo "   ✓ Primera carga es lenta, pero caché lo resuelve"
echo ""

echo "📚 DOCUMENTACIÓN:"
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "• Streamlit Docs: https://docs.streamlit.io"
echo "• Streamlit Cloud: https://share.streamlit.io"
echo "• GitHub Help: https://docs.github.com"
echo ""

echo "═══════════════════════════════════════════════════════════════════════════"
echo "✅ ¡FELICIDADES! Ahora tienes un dashboard en producción 🎉"
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""
